language: android
dist: trusty

android:
  components:
    - build-tools-25.0.1
    - android-25
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
